name: flutterdemo
description: "Flutter Demo"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.1
  qr_code_dart_scan: ^0.9.1
#  #  离线依赖
#  packagedemo:
#    path: C:/Users/Administrator/WebstormProjects/packagedemo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
